In [ ]:
# Lab03 Numpy Basics

In [1]:
# NumPy Basics
import numpy as np

s = np.arange(12)
print(s)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [2]:
# 1) Show all element of s
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
# 2) Show the third element of s
print(s[2])

# 2) Show the last element of s
print(s[-1])

2
11


In [5]:
# 3) Show the third to last element of s
print(s[2:])

# Show the third to seventh element of s
print(s[2:7])


[ 2  3  4  5  6  7  8  9 10 11]
[2 3 4 5 6]


In [8]:

# 4) Show the total of s
print( sum(s)) 

# Show the smallest value of s
print( s.min())

# Show the average value of s
print(s.mean())

# Show the smallest value of s
print (s.max())

66
0
5.5
11


In [9]:
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
# 5) if array change values, will s change values too? why?
# show s values
arry = s
arry[1]= -1
print(s)
print(arry)

[ 0 -1  2  3  4  5  6  7  8  9 10 11]
[ 0 -1  2  3  4  5  6  7  8  9 10 11]


In [13]:
data = [[1,2,3],
        [4,5,6],
        [7,8,9]]
print(data)

matrix = np.array(data)
print(matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
data = [[1.5,2,3],
        [4,5,6],
        [7,8,9]]
print(data)
print('--------------')
matrix = np.array(data)
print(matrix)

[[1.5, 2, 3], [4, 5, 6], [7, 8, 9]]
--------------
[[1.5 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [16]:
# 6)Show the element of first row of second col of matrix
print(matrix[0,1])

# 6)Show the element of second row of first col of matrix
print(matrix[1,0])

2.0
4.0


In [18]:
# 7 )Show all elements of first row in matrix
print( matrix[0] )

#  Show all elements of second row in matrix
print( matrix[1] )


[1.5 2.  3. ]
[4. 5. 6.]


In [19]:
# 8) Show all elements of first col in matrix
print( matrix[:,0] )

# Show all elements of third col in matrix
print( matrix[:,2] )


[1.5 4.  7. ]
[3. 6. 9.]


In [20]:
print( matrix)
# Show second rows, and second col to last col's elements in matrix
print( matrix[1, 1:] )

[[1.5 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]
[5. 6.]


In [21]:
print(matrix)
# 5) Show the total of s
print( sum(s)) 

# Show the smallest value of s
print( s.min())

# Show the average value of s
print(s.mean())

# Show the smallest value of s
print (s.max())

# The sum of second col
print( matrix[:,1].sum())


[[1.5 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]
64
-1
5.333333333333333
11
15.0


In [23]:
# show the max of first row
matrix[0]
matrix[0].max()

3.0

In [24]:
matrix = np.array([[1, 2, 3, 4],
          [5, 6, 7, 8]])

print(matrix)
print(len(matrix[0]))
print(len(matrix[:,0]))

# Compute sum of row

#def getSum_rwo(matrix)

[[1 2 3 4]
 [5 6 7 8]]
4
2
